# Generated by Django 5.0.1 on 2024-01-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='buy_date',
            field=models.DateField(null=True),
        ),
    ]
